modLoader="javafml"
loaderVersion="[24,]"
logoFile="logo.png"
authors="Pugz"

[[mods]]
    modId="colormatic"
    version="1.0.1"
    displayName="Colormatic"
    description='''
    Build better with more color!
    '''
    [[dependencies.colormatic]]
        modId="forge"
        mandatory=true
        versionRange="[${forge_version},)"
        ordering="NONE"
        side="BOTH"