modLoader="javafml"
loaderVersion="[24,]"
logoFile="logo.png"
authors="Pugz"

[[mods]]
    modId="colormatic"
    version="1.0.1"
    displayName="Colormatic"
    description='''
    Build better with more color!
    '''
    [[dependencies.colormatic]]
        modId="pugzlib"
        mandatory=true
        versionRange="[1.4-34,)"
        ordering="AFTER"
        side="BOTH"